// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsy2b8oB_mBr1bbGDuuwZbULwvwkd5_ZY',
    appId: '1:939078063078:web:1fa47c9980e233b1767c27',
    messagingSenderId: '939078063078',
    projectId: 'pomodoro-80a33',
    authDomain: 'pomodoro-80a33.firebaseapp.com',
    storageBucket: 'pomodoro-80a33.firebasestorage.app',
    measurementId: 'G-YR3QLT7GPY',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8ewzoNSiIgZNOICSR-ZwHtqqIZ3IccGM',
    appId: '1:939078063078:ios:39763f19fa8f13a3767c27',
    messagingSenderId: '939078063078',
    projectId: 'pomodoro-80a33',
    storageBucket: 'pomodoro-80a33.firebasestorage.app',
    androidClientId: '939078063078-aoupeh4gu1edurbeujncdlqo1vnkhq6n.apps.googleusercontent.com',
    iosClientId: '939078063078-s4ohc4a1a7eg3f1akakgk2i985stbgl7.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyPlannerPomodoro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8ewzoNSiIgZNOICSR-ZwHtqqIZ3IccGM',
    appId: '1:939078063078:ios:39763f19fa8f13a3767c27',
    messagingSenderId: '939078063078',
    projectId: 'pomodoro-80a33',
    storageBucket: 'pomodoro-80a33.firebasestorage.app',
    androidClientId: '939078063078-aoupeh4gu1edurbeujncdlqo1vnkhq6n.apps.googleusercontent.com',
    iosClientId: '939078063078-s4ohc4a1a7eg3f1akakgk2i985stbgl7.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyPlannerPomodoro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsy2b8oB_mBr1bbGDuuwZbULwvwkd5_ZY',
    appId: '1:939078063078:web:ac3fa85da7a3a60d767c27',
    messagingSenderId: '939078063078',
    projectId: 'pomodoro-80a33',
    authDomain: 'pomodoro-80a33.firebaseapp.com',
    storageBucket: 'pomodoro-80a33.firebasestorage.app',
    measurementId: 'G-H212YNDV1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs16DBCJirVGnzeIViFHxjn8VSXa5OunI',
    appId: '1:939078063078:android:dbdef713246610a4767c27',
    messagingSenderId: '939078063078',
    projectId: 'pomodoro-80a33',
    storageBucket: 'pomodoro-80a33.firebasestorage.app',
  );

}